spring.application.name=smart-link-shortener
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_link_shortener
spring.datasource.username=postgres
spring.datasource.password=012400zzz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Access token het han sau 15 phut (900000 ms)
jwt.access-token-expiration=900000
# Refresh token het han sau 7 ngay (604800 giay)
jwt.refresh-token-expiration=604800

# ===== Redis Configuration =====
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=   # Bo trong neu Redis local khong dat password
spring.data.redis.timeout=2000ms

# ===== URL Security & Safe Browsing Configuration =====
app.security.self-domains=localhost,127.0.0.1,0.0.0.0
app.security.allow-localhost-targets=false
app.security.check-reachability=true
# Điền Google Safe Browsing API Key tại đây (nếu để trống, hệ thống sẽ bỏ qua kiểm tra Google Safe Browsing)
google.safebrowsing.api-key=AIzaSyBkw-ZePuwngrJPpl9kuaiS8uoVK59wRoc

# Tat Kafka auto-config neu chua dung (de tranh loi startup)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration